-- Création de la table `favorites` pour Supabase
-- Exécutez ce SQL dans Supabase SQL editor ou via psql avec la connexion fournie.

CREATE TABLE IF NOT EXISTS public.favorites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL,
  channel_id text NOT NULL,
  channel_name text,
  country text,
  logo text,
  categories jsonb DEFAULT '[]'::jsonb,
  streams jsonb DEFAULT '[]'::jsonb,
  inserted_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),
  CONSTRAINT favorites_user_channel_unique UNIQUE (user_id, channel_id)
);

-- Index utile
CREATE INDEX IF NOT EXISTS favorites_user_id_idx ON public.favorites(user_id);

-- Activer RLS
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;

-- Politique : les utilisateurs authentifiés peuvent sélectionner leurs propres favoris
CREATE POLICY "select_own_favorites" ON public.favorites
  FOR SELECT
  USING (user_id = auth.uid());

-- Politique : les utilisateurs authentifiés peuvent insérer leurs propres favoris
CREATE POLICY "insert_own_favorites" ON public.favorites
  FOR INSERT
  WITH CHECK (user_id = auth.uid());

-- Politique : les utilisateurs authentifiés peuvent supprimer leurs propres favoris
CREATE POLICY "delete_own_favorites" ON public.favorites
  FOR DELETE
  USING (user_id = auth.uid());

-- Politique : les utilisateurs authentifiés peuvent mettre à jour leurs propres favoris
CREATE POLICY "update_own_favorites" ON public.favorites
  FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Optionnel : pour que l'API REST expose la table aux utilisateurs authentifiés
GRANT SELECT, INSERT, UPDATE, DELETE ON public.favorites TO authenticated;

-- Vérification : retourne 1 si tout est OK
SELECT 1 AS ok;
